remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Conociendo la Ingeniería en Biomédica]
description: [Con esta página web, tenemos la intención de dar a conocer las ramas de la ingeniería en biomédica y sus campos laborales.]
